name: Push Release

on:
  release:
    types:
      - released

jobs:
  push-to-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: release
      - name: Push to release
        run: |
          git checkout ${{ github.event.release.target_commitish }}
          git merge -s ours release
          git checkout release
          git merge ${{ github.event.release.target_commitish }}
          git push
